############################################################
# Shell preferences (loaded from ~/.lpy.conf)
############################################################
LPY_PROMPT="standard"
LPY_USE_BAT=0
LPY_USE_EZA=0
LPY_EZA_ICONS=0
LPY_SYNTAX_HIGHLIGHTING=0
LPY_GIT_ALIASES=0
LPY_GIT_FZF=0
LPY_CLIPBOARD=0

LPY_CONF="$HOME/.lpy.conf"
[[ -f "$LPY_CONF" ]] && source "$LPY_CONF"

_lpy_label() {
  if [[ "$1" == "1" ]]; then
    printf "\033[32mon\033[0m"
  else
    printf "\033[31moff\033[0m"
  fi
}

_lpy_prompt() {
  local desc="$1" current="$2"
  local hint
  if [[ "$current" == "1" ]]; then hint="Y/n"; else hint="y/N"; fi
  printf "  %s [%s]: " "$desc" "$hint"
  local answer
  read -r answer
  case "$answer" in
    [Yy]) echo 1 ;;
    [Nn]) echo 0 ;;
    *)    echo "$current" ;;
  esac
}

_lpy_prompt_style() {
  local BOLD="\033[1m" DIM="\033[2m" CYAN="\033[36m" YELLOW="\033[33m" GREEN="\033[32m" RESET="\033[0m"
  local current="$LPY_PROMPT"

  printf "\n  ${BOLD}Prompt style${RESET} ${DIM}(current: ${current})${RESET}\n\n"
  printf "  ${BOLD}[1]${RESET} Minimal\n"
  printf "      ${YELLOW}~/code/lopay-api${RESET} %%\n\n"
  printf "  ${BOLD}[2]${RESET} Standard\n"
  printf "      ${CYAN}ubuntu@lopay-dev${RESET}:${YELLOW}~/code/lopay-api${RESET} ${GREEN}(main)${RESET} %%\n\n"
  printf "  ${BOLD}[3]${RESET} Full\n"
  printf "      ${CYAN}ubuntu@lopay-dev${RESET}:${YELLOW}~/code/lopay-api${RESET} ${GREEN}(main)${RESET}${DIM} node:22.14${RESET} %%\n\n"

  local choice
  printf "  Choice [2]: "
  read -r choice
  case "$choice" in
    1) echo "minimal" ;;
    3) echo "full" ;;
    *) echo "standard" ;;
  esac
}

_lpy_setup() {
  local BOLD="\033[1m" DIM="\033[2m" CYAN="\033[36m" GREEN="\033[32m" RESET="\033[0m"

  printf "\n${BOLD}${CYAN}Lopay Dev Environment${RESET}\n"
  printf "${DIM}Configure your shell preferences. Press Enter to keep current value.${RESET}\n\n"

  LPY_PROMPT=$(_lpy_prompt_style)
  LPY_USE_BAT=$(_lpy_prompt "Use bat as cat replacement (syntax highlighting)" "$LPY_USE_BAT")
  LPY_USE_EZA=$(_lpy_prompt "Use eza as ls replacement (colors, grouping)" "$LPY_USE_EZA")
  LPY_EZA_ICONS=$(_lpy_prompt "Show icons in eza output (needs Nerd Font on your terminal)" "$LPY_EZA_ICONS")
  LPY_SYNTAX_HIGHLIGHTING=$(_lpy_prompt "Enable zsh syntax highlighting" "$LPY_SYNTAX_HIGHLIGHTING")
  LPY_GIT_ALIASES=$(_lpy_prompt "Enable git aliases (gs, ga, gc, gp, ...)" "$LPY_GIT_ALIASES")
  LPY_GIT_FZF=$(_lpy_prompt "Enable git fzf helpers (gcof, grf, glf)" "$LPY_GIT_FZF")
  LPY_CLIPBOARD=$(_lpy_prompt "Enable clipboard integration (xclip)" "$LPY_CLIPBOARD")

  cat > "$LPY_CONF" <<EOF
# Lopay shell preferences — generated by 'lpy setup'
LPY_PROMPT=$LPY_PROMPT
LPY_USE_BAT=$LPY_USE_BAT
LPY_USE_EZA=$LPY_USE_EZA
LPY_EZA_ICONS=$LPY_EZA_ICONS
LPY_SYNTAX_HIGHLIGHTING=$LPY_SYNTAX_HIGHLIGHTING
LPY_GIT_ALIASES=$LPY_GIT_ALIASES
LPY_GIT_FZF=$LPY_GIT_FZF
LPY_CLIPBOARD=$LPY_CLIPBOARD
EOF

  printf "\n${BOLD}${GREEN}Saved.${RESET} Restart your shell or run: ${BOLD}source ~/.zshrc${RESET}\n"
}

_lpy_config() {
  local BOLD="\033[1m" DIM="\033[2m" RESET="\033[0m"

  printf "\n${BOLD}Current preferences${RESET}"
  if [[ -f "$LPY_CONF" ]]; then
    printf " ${DIM}(~/.lpy.conf)${RESET}\n\n"
  else
    printf " ${DIM}(defaults — run 'lpy setup' to customise)${RESET}\n\n"
  fi

  printf "  prompt style      \033[1m%s\033[0m\n" "$LPY_PROMPT"
  printf "  bat as cat        %b\n" "$(_lpy_label "$LPY_USE_BAT")"
  printf "  eza as ls         %b\n" "$(_lpy_label "$LPY_USE_EZA")"
  printf "  eza icons         %b\n" "$(_lpy_label "$LPY_EZA_ICONS")"
  printf "  syntax highlight  %b\n" "$(_lpy_label "$LPY_SYNTAX_HIGHLIGHTING")"
  printf "  git aliases       %b\n" "$(_lpy_label "$LPY_GIT_ALIASES")"
  printf "  git fzf helpers   %b\n" "$(_lpy_label "$LPY_GIT_FZF")"
  printf "  clipboard         %b\n" "$(_lpy_label "$LPY_CLIPBOARD")"
  echo
}

lpy() {
  case "${1:-}" in
    init)   source "$HOME/lpy-init.sh" ;;
    setup)  _lpy_setup ;;
    config) _lpy_config ;;
    reset)
      rm -f "$LPY_CONF"
      printf "\033[1mReset to defaults.\033[0m Restart your shell or run: \033[1msource ~/.zshrc\033[0m\n"
      ;;
    *)
      printf "\n\033[1mlpy\033[0m — Lopay dev environment config\n\n"
      printf "  \033[1mlpy init\033[0m     First-time setup wizard\n"
      printf "  \033[1mlpy setup\033[0m    Configure shell preferences\n"
      printf "  \033[1mlpy config\033[0m   Show current preferences\n"
      printf "  \033[1mlpy reset\033[0m    Reset to defaults\n"
      echo
      ;;
  esac
}

############################################################
# nvm Setup
############################################################
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

############################################################
# Auto-switch Node version based on .nvmrc
############################################################
autoload -U add-zsh-hook

load-nvmrc() {
  command -v nvm >/dev/null 2>&1 || return

  local nvmrc_path="$PWD/.nvmrc"
  if [ -f "$nvmrc_path" ]; then
    local wanted
    wanted="$(<"$nvmrc_path")"

    if ! nvm ls "$wanted" >/dev/null 2>&1; then
      nvm install >/dev/null 2>&1
    fi

    if [ "$(nvm current 2>/dev/null)" != "v${wanted#v}" ]; then
      nvm use >/dev/null 2>&1
    fi
  else
    local def
    def="$(nvm version default 2>/dev/null)"
    if [ -n "$def" ] && [ "$(nvm current 2>/dev/null)" != "$def" ]; then
      nvm use default >/dev/null 2>&1
    fi
  fi
}

add-zsh-hook chpwd load-nvmrc
load-nvmrc

############################################################
# Prompt
############################################################
autoload -Uz vcs_info
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
zstyle ':vcs_info:git:*' formats '(%b)'
zstyle ':vcs_info:git:*' actionformats '(%b|%a)'
setopt PROMPT_SUBST

_lpy_node_version() {
  local v
  v="$(node -v 2>/dev/null)" && echo " node:${v#v}"
}

case "$LPY_PROMPT" in
  minimal)
    PROMPT='%F{yellow}%~%f %# '
    ;;
  full)
    PROMPT='%F{cyan}%n@%m%f:%F{yellow}%~%f %F{green}${vcs_info_msg_0_}%f%F{dim}$(_lpy_node_version)%f %# '
    ;;
  *)  # standard
    PROMPT='%F{cyan}%n@%m%f:%F{yellow}%~%f %F{green}${vcs_info_msg_0_}%f %# '
    ;;
esac

############################################################
# QoL
############################################################

# Syntax highlighting
(( LPY_SYNTAX_HIGHLIGHTING )) && \
  [ -r /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ] && \
  source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Aliases — always on
alias ..="cd .."
alias ...="cd ../.."
alias hs='history 1 | grep'
alias ip='curl -s ifconfig.me && echo'
alias elast='fc'
alias clod='claude'
alias claude:install='npm install -g @anthropic-ai/claude-code'

# Conditional aliases
(( LPY_USE_BAT )) && alias cat="bat"

if (( LPY_USE_EZA )); then
  _eza_flags="--group-directories-first"
  (( LPY_EZA_ICONS )) && _eza_flags="--icons $_eza_flags"
  alias ls="eza $_eza_flags"
  alias ll="eza -lh $_eza_flags"
  alias la="eza -lha $_eza_flags"
  unset _eza_flags
fi

if (( LPY_CLIPBOARD )); then
  alias cip='curl -s ifconfig.me | xclip -selection clipboard'
fi

# mkcd: make a directory then cd into it
mkcd() { mkdir -p "$1" && cd "$1"; }

# sudo last command
please() {
  local last_cmd
  last_cmd="$(fc -ln -1)"
  if [ -n "$last_cmd" ]; then
    sudo $last_cmd
  else
    echo "No previous command found."
  fi
}

# del: Prompt once before deleting file or directory
del() {
  local target="$1"
  local RED="\033[31m" BLUE="\033[34m" BOLD="\033[1m" DIM="\033[2m" RESET="\033[0m"

  [[ -z "$target" ]] && { echo "Usage: del <file-or-directory>"; return 1; }
  [[ ! -e "$target" ]] && { echo "No such file or directory: $target"; return 1; }

  local NAME COLORED_NAME
  if [[ -d "$target" ]]; then
    NAME="${target%/}/"
    COLORED_NAME="${BLUE}${BOLD}${NAME}${RESET}"
  else
    NAME="$target"
    COLORED_NAME="${RED}${BOLD}${NAME}${RESET}"
  fi

  printf "Delete %b? ${DIM}[Enter=delete, Esc=cancel]${RESET} " "$COLORED_NAME"
  local key
  IFS= read -rsk1 key
  echo

  if [[ "$key" == $'\e' ]]; then
    echo "Aborted."
    return 130
  fi

  if [[ -z "$key" || "$key" == $'\n' || "$key" == 'y' || "$key" == 'Y' ]]; then
    rm -rf -- "$target"
    echo "'$NAME' deleted."
    return 0
  else
    echo "Aborted."
    return 1
  fi
}

# Time how long a command takes
timer() {
  local start end secs status
  start=$(date +%s)
  "$@"
  status=$?
  end=$(date +%s)
  secs=$((end - start))

  local BOLD="\033[1m" RED="\033[31m" GREEN="\033[32m" RESET="\033[0m"
  local COLOR=$([ $status -eq 0 ] && echo "$GREEN" || echo "$RED")

  printf "%bTook %ds%b\n" "${BOLD}${COLOR}" "$secs" "$RESET"
  return $status
}

# Copy name of current git branch
copybranch() {
  if (( LPY_CLIPBOARD )); then
    git rev-parse --abbrev-ref HEAD | xclip -selection clipboard
    echo "Branch copied."
  else
    git rev-parse --abbrev-ref HEAD
  fi
}

# Guided connection to postgres (using pgcli)
pgc() {
  command -v pgcli >/dev/null 2>&1 || { echo "pgcli not found. pipx install pgcli"; return 127; }

  local host port user db pass
  read -r "host?Host [localhost]: "
  host=${host:-localhost}

  read -r "port?Port [5432]: "
  port=${port:-5432}

  read -r "user?User [${USER}]: "
  user=${user:-$USER}

  read -r "db?Database (required): "
  if [[ -z "$db" ]]; then
    echo "Database name is required."; return 1
  fi

  read -rs "pass?Password (leave blank to let pgcli prompt): "
  echo

  if [[ -n "$pass" ]]; then
    PGPASSWORD="$pass" pgcli -h "$host" -p "$port" -U "$user" "$db"
  else
    pgcli -h "$host" -p "$port" -U "$user" "$db"
  fi
}

# Kill whatever is using a given port
killport() { lsof -ti tcp:"$1" | xargs -r kill -9; }

# Show process using a given port
checkport() {
  local port=$1
  if [[ -z "$port" ]]; then
    echo "Usage: checkport <port>"
    return 1
  fi
  lsof -nP -iTCP:$port -sTCP:LISTEN | awk 'NR==1 || /LISTEN/'
}

# Interactive TS REPL
tsrepl() {
  npx ts-node --transpile-only --interactive
}

############################################################
# Git QoL + ghelp
############################################################

if (( LPY_GIT_ALIASES )); then
  alias gs='git status -sb'
  alias ga='git add'
  alias gap='git add -p'
  alias gc='git commit -v'
  alias gca='git commit -v --amend'
  alias gco='git checkout'
  alias gb='git branch -vv'
  alias gbdm='git branch --merged main | grep -vE "^\*? *main$" | xargs -r git branch -d'
  alias gp='git push'
  alias gpl='git pull --rebase --autostash'
  alias gl='git log --oneline --graph --decorate --boundary'
  alias glg='git log --graph --pretty=format:"%C(auto)%h %C(bold blue)%ad %Creset%<(60,trunc)%s %C(italic dim)%an%Creset %C(green)%d" --date=short'

  # Create a new branch (optionally from a base branch/ref)
  gnew() {
    local name="$1"
    local base="$2"

    if [[ -z "$name" ]]; then
      echo "Usage: gnew <branch-name> [base-branch-or-ref]"
      return 1
    fi

    if [[ -n "$base" ]]; then
      git checkout -b "$name" "$base"
    else
      git checkout -b "$name"
    fi
  }

  # ghelp: discover git commands & usage
  typeset -A __GIT_HELP_DESC __GIT_HELP_USAGE

  __GIT_HELP_DESC=(
    gs    "git status (short)"
    ga    "git add <paths>"
    gap   "git add -p (patch)"
    gc    "git commit -v"
    gca   "git commit -v --amend"
    gco   "git checkout <branch|--|path>"
    gnew  "create and checkout a new branch (optionally from base)"
    gb    "git branch -vv"
    gbdm  "delete branches merged into main"
    gp    "git push"
    gpl   "git pull --rebase --autostash"
    gl    "log: oneline graph"
    glg   "log: pretty graph with dates/authors"
  )

  __GIT_HELP_USAGE=(
    gs  $'Usage: gs\nShows short status with branch/changes.\nEquivalent: git status -sb'
    ga  $'Usage: ga <path...>\nStage files for the next commit.'
    gap $'Usage: gap\nInteractive patch staging (add -p).'
    gc  $'Usage: gc\nOpens commit editor with verbose diff (commit.verbose).'
    gca $'Usage: gca\nAmends the last commit (keeps message unless editor configured).'
    gco $'Usage: gco <branch>\n       gco -- <path>\nSwitch branch or restore paths.'
    gnew $'Usage: gnew <branch-name> [base]\nCreates and checks out a new branch.\nIf base is provided, branch is created from that ref; otherwise from current branch.'
    gb  $'Usage: gb\nList branches with upstream and last commit.'
    gbdm $'Usage: gbdm\nDelete all branches fully merged into main (except main).'
    gp  $'Usage: gp\nPush current branch.'
    gpl $'Usage: gpl\nPull with rebase and autostash.'
    gl  $'Usage: gl\nCompact commit graph (oneline).'
    glg $'Usage: glg\nPretty, wrapped commit graph with date/author/refs.'
  )

  if (( LPY_GIT_FZF )); then
    # Fuzzy checkout any branch (local/remote)
    gcof() {
      if ! command -v fzf >/dev/null 2>&1; then
        echo "gcof needs fzf (apt install fzf)"; return 127
      fi
      git for-each-ref --format='%(refname:short)' refs/heads refs/remotes \
      | sed 's#^remotes/[^/]*/##' | sort -u \
      | fzf --height=40% --reverse --prompt='branch> ' \
      | xargs -r git checkout
    }

    # Fuzzy add from git status (multi-select)
    grf() {
      if ! command -v fzf >/dev/null 2>&1; then
        echo "grf needs fzf (apt install fzf)"; return 127
      fi
      git -c color.status=always status --short \
      | fzf --ansi --multi --height=60% --reverse --prompt='stage> ' \
      | awk '{print $2}' | xargs -r git add
    }

    # Fuzzy browse commits with preview
    glf() {
      if ! command -v fzf >/dev/null 2>&1; then
        echo "glf needs fzf (apt install fzf)"; return 127
      fi
      git log --oneline --decorate --graph --color=always \
      | fzf --ansi --no-sort --reverse --height=80% \
            --preview 'git show --color=always {1}' \
            --prompt='commit> ' \
            --bind 'enter:execute(git show {1} | less -R)'
    }

    __GIT_HELP_DESC+=(
      gcof  "fzf: checkout any branch (local/remote)"
      grf   "fzf: interactively stage files"
      glf   "fzf: browse commits with preview"
    )
    __GIT_HELP_USAGE+=(
      gcof $'Usage: gcof\nFuzzy-pick a branch (local/remote) to checkout.\nRequires: fzf'
      grf $'Usage: grf\nFuzzy-select files from git status to stage (multi-select).\nRequires: fzf'
      glf $'Usage: glf\nFuzzy browse commits; Enter to open commit in less; right pane shows diff.\nRequires: fzf'
    )
  fi

  ghelp() {
    local subcmd="$1"
    shift || true

    if [[ -n "$subcmd" && "$subcmd" != "grep" ]]; then
      local key
      for key in "${(@k)__GIT_HELP_USAGE}"; do
        if [[ "$key" == "$subcmd" ]]; then
          print -r -- "$__GIT_HELP_USAGE[$key]"
          return 0
        fi
      done
      local matches=()
      for key in "${(@k)__GIT_HELP_DESC}"; do
        if [[ "$key" == *"$subcmd"* || "${__GIT_HELP_DESC[$key]}" == *"$subcmd"* ]]; then
          matches+="$key"
        fi
      done
      if (( ${#matches} )); then
        for key in "${matches[@]}"; do
          printf '%-6s %s\n' "$key" "${__GIT_HELP_DESC[$key]}"
        done | sort
        return 0
      else
        echo "ghelp: no match for '$subcmd'"; return 1
      fi
    fi

    if [[ "$subcmd" == "grep" ]]; then
      local pat="$1"
      [[ -z "$pat" ]] && { echo "Usage: ghelp grep <pattern>"; return 1; }
      for key in "${(@k)__GIT_HELP_DESC}"; do
        if [[ "$key" == *"$pat"* || "${__GIT_HELP_DESC[$key]}" == *"$pat"* ]]; then
          printf '%-6s %s\n' "$key" "${__GIT_HELP_DESC[$key]}"
        fi
      done | sort
      return 0
    fi

    for key in "${(@k)__GIT_HELP_DESC}"; do
      printf '%-6s %s\n' "$key" "${__GIT_HELP_DESC[$key]}"
    done | sort
  }
fi

############################################################
# PATH additions
############################################################

# Google Cloud SDK
if [ -f "$HOME/google-cloud-sdk/path.zsh.inc" ]; then . "$HOME/google-cloud-sdk/path.zsh.inc"; fi
if [ -f "$HOME/google-cloud-sdk/completion.zsh.inc" ]; then . "$HOME/google-cloud-sdk/completion.zsh.inc"; fi

export PATH="$HOME/.local/bin:$PATH"

# pnpm
export PNPM_HOME="$HOME/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

############################################################
# MOTD + first-login auto-trigger
############################################################
if [[ -o interactive ]]; then
  source "$HOME/motd.sh" 2>/dev/null
  if [[ ! -f "$HOME/.lpy-init-done" ]]; then
    lpy init
  fi
fi
