#!/bin/bash
echo ''
echo '$$\                                                     $$\                     '
echo '$$ |                                                    $$ |                    '
echo '$$ | $$$$$$\   $$$$$$\   $$$$$$\  $$\   $$\        $$$$$$$ | $$$$$$\ $$\    $$\ '
echo '$$ |$$  __$$\ $$  __$$\  \____$$\ $$ |  $$ |      $$  __$$ |$$  __$$\\$$\  $$  |'
echo '$$ |$$ /  $$ |$$ /  $$ | $$$$$$$ |$$ |  $$ |      $$ /  $$ |$$$$$$$$ |\$$\$$  / '
echo '$$ |$$ |  $$ |$$ |  $$ |$$  __$$ |$$ |  $$ |      $$ |  $$ |$$   ____| \$$$  /  '
echo '$$ |\$$$$$$  |$$$$$$$  |\$$$$$$$ |\$$$$$$$ |      \$$$$$$$ |\$$$$$$$\   \$  /   '
echo '\__| \______/ $$  ____/  \_______| \____$$ |       \_______| \_______|   \_/    '
echo '              $$ |                $$\   $$ |                                    '
echo '              $$ |                \$$$$$$  |                                    '
echo '              \__|                 \______/                                     '
echo ''
echo '  ==========================================='
echo '    Welcome to your Lopay dev environment!'
echo '    You are all set to build something great.'
echo '  ==========================================='
echo ''
echo '  BEFORE YOU START: Add your SSH key to GitHub'
echo ''
echo '  1. Copy your public key:'
echo '     cat ~/.ssh/id_ed25519.pub'
echo ''
echo '  2. Go to: https://github.com/settings/ssh/new'
echo ''
echo '  3. Paste the key and save.'
echo ''
echo '  THEN: Clone the repos by running:'
echo '     ~/setup-repos.sh'
echo ''
echo '  CUSTOMISE YOUR SHELL (optional):'
echo '     lpy setup'
echo ''
echo '  Happy coding! :)'
echo ''
